NAME := st-str-019
SRCS := $(shell find -L ./ -name "*.[cS]")
SRCS += $(AM_HOME)/am/src/linknan/src/cmo.c
INC_DIR := $(AM_HOME)/drivers/include
INC_DIR += $(AM_HOME)/am/src/linknan/include

include $(AM_HOME)/Makefile.app
