NAME := st-str-009
SRCS := $(shell find -L ./ -name "*.[cS]")
SRCS += $(AM_HOME)/drivers/src/dw_axi_dmac.c
SRCS += $(AM_HOME)/drivers/src/dw_apb_timer.c
INC_DIR := $(AM_HOME)/drivers/include

include $(AM_HOME)/Makefile.app
